site_url: https://amkisko.github.io
host: amkisko.github.io
sitemap: sitemap.xml

sitemap_generate:
  static:
    - /
    - posts.html
  globs:
    - posts/*.html

indexnow:
  enabled: true
  key: 1297c37c84c8e45dfacd95344d779a49
  key_location: https://amkisko.github.io/1297c37c84c8e45dfacd95344d779a49.txt
  endpoint: https://api.indexnow.org/indexnow
  batch_size: 10000

bing:
  enabled: false
  client_id:
  client_secret:
  redirect_uri: http://127.0.0.1:8765/callback
  scope: webmaster.manage
  batch_size: 500

sitemap_ping:
  enabled: true
  endpoints:
    - https://www.bing.com/ping?sitemap=
